services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=loan-calculator'
      - 'POSTGRES_PASSWORD=example'
      - 'POSTGRES_USER=example'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: