spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan-calculator
    username: example
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
#    show-sql: true

server:
  servlet:
    context-path: /leanpay